spring.application.name=familytask-backend

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/familytask
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000


# Google OAuth ${CLIENT_ID}
app.google.client-id=${CLIENT_ID}
app.google.client-secret=${CLIENT_SECRET}
app.google.redirect-uri=http://localhost:4200/auth/callback
app.google.token-endpoint=https://oauth2.googleapis.com/token
app.google.userinfo-endpoint=https://www.googleapis.com/oauth2/v2/userinfo

# Invitaciones
app.invitation.expiration-days=7
app.invitation.base-url=http://localhost:4200/invitation

# Ollama Cloud
spring.ai.model.chat=none
spring.threads.virtual.enabled=true
app.ollama.base-url=http://localhost:11434
app.ollama.api-key=${OLLAMA_API_KEY}
app.ollama.model=${OLLAMA_MODEL:deepseek-v3.1:671b-cloud}
app.ollama.temperature=0.85
app.ollama.top-p=0.9
app.ollama.top-k=40
app.ollama.repeat-penalty=1.15
app.ollama.timeout-seconds=180
app.ollama.num-predict=600
app.ollama.parallel-wait-ms=25000

